### ISSUE TITLE
Validate/Tshoot k8s hostNetwork

### ISSUE THREAD

**Issue by nerdalert** [nexodus-io/nexodus#1535]
Ran into an issue where `hostNetwork: true` was not getting wg traffic off the host. The issue was in an EC2 OCP deployment so we should look at that as well as vanilla k8s.

The following was failing. If you remove `hostNetwork: true` everything works in the symmetric NAT environment:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nexd
  namespace: <NAMESPACE>
spec:
  hostNetwork: true
  hostAliases:
    - ip: <API_SERVER>
      hostnames:
        - try.nexodus.127.0.0.1.nip.io
        - api.try.nexodus.127.0.0.1.nip.io
        - auth.try.nexodus.127.0.0.1.nip.io
  containers:
  - name: nexd-container
    image: quay.io/nexodus/nexd:latest
    command:
      - nexd
    args:
      - --username
      - <USERNAME>
      - --password
      - <PASSWORD>
      - --insecure-skip-tls-verify
      - https://try.nexodus.127.0.0.1.nip.io
    securityContext:
      privileged: true
```
